<a href="https://colab.research.google.com/github/heugyu/notebook/blob/master/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 외부 파일 업로드

In [7]:
from google.colab import files

# 파일 업로드 기능 실행
uploaded = files.upload()

for fn in uploaded.keys():
    # 업로드된 파일 정보 출력
    print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

Saving BINANCE_BTCUSDT_30.csv to BINANCE_BTCUSDT_30.csv
User uploaded file "BINANCE_BTCUSDT_30.csv" with length 10523769 bytes

In [8]:
import io
import pandas as pd 

# 업로드된 파일을 읽기 위해 io package의 StringIO 명령어 사용
df = pd.read_csv(io.StringIO(uploaded['BINANCE_BTCUSDT_30.csv'].decode('utf-8')))

df.head()

           time              date  ...  A/D Buy MA  A/D Sell MA
0  1.546301e+09  2019-01-01 09:00  ...         NaN          NaN
1  1.546303e+09  2019-01-01 09:30  ...         NaN          NaN
2  1.546304e+09  2019-01-01 10:00  ...         NaN          NaN
3  1.546306e+09  2019-01-01 10:30  ...         NaN          NaN
4  1.546308e+09  2019-01-01 11:00  ...         NaN          NaN

[5 rows x 50 columns]